### ISSUE TITLE
Make module images localizable for KLM Submission Pipeline

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#1079]
BTP Manager deployment should contain all the images required by the module (BTP Manager image as operator and SAP BTP service operator as operand).

**AC**:
- [x] 1. BTP Manager image is stored in `europe-docker.pkg.dev/kyma-project/prod` registry.
- [x] 2. SAP BTP service operator images are stored in `europe-docker.pkg.dev/kyma-project/prod` registry.
- [x] 3. SAP BTP service operator images are referenced in BTP Manager's deployment as environment variables in the controller container:
```
env:
- name: sap-btp-service-operator
  value: "europe-docker.pkg.dev/kyma-project/prod/external/sap-btp-service-operator/controller:<VERSION>"
- name: kube-rbac-proxy
  value: "europe-docker.pkg.dev/kyma-project/prod/external/kube-rbac-proxy:<VERSION>"
``` 

Refs:
[Make module images localizable](https://github.com/kyma-project/kyma/issues/18798)
[BTP Operator - Make module images localizable](https://github.com/kyma-project/kyma/issues/18801)

[OCM - Open Component Model](https://github.com/open-component-model/ocm)
[Kyma module as OCM component](https://github.com/kyma-project/lifecycle-manager/issues/1587)
[[Restricted Markets] Support Docker image localization ](https://github.com/kyma-project/lifecycle-manager/issues/1858)
[Handling Modules in Restricted Environments](https://github.com/kyma-project/lifecycle-manager/issues/1867)

[[Submission Pipeline] Read module images from raw manifest](https://github.com/kyma-project/modulectl/issues/235)
[[Restricted Market] Validate module images are in europe-docker.pkg.dev/kyma-project/prod/](https://github.com/kyma-project/modulectl/issues/263)

**Comment by jaroslaw-pieszka** [comment]
We need to add reference to btp-operator image:
```yaml
kind: Deployment
metadata:
  name: btp-manager-controller-manager
  namespace: kyma-system
spec:
  template:
    spec:
      containers:
      - image: europe-docker.pkg.dev/kyma-project/prod/btp-manager:1.2.9
        env:
        - name: sap-btp-service-operator
          value: "europe-docker.pkg.dev/kyma-project/prod/external/sap-btp-service-operator/controller:v0.6.4"
```

**Comment by szwedm** [comment]
Module managed images are added to the module deployment manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: btp-manager.kyma-project.io
    kyma-project.io/module: btp-operator
  name: btp-manager-controller-manager
  namespace: kyma-system
spec:
  ...
  template:
    ...
    spec:
      containers:
          name: manager
          image: europe-docker.pkg.dev/kyma-project/prod/btp-manager:1.2.12
          ...
          env:
            - name: sap-btp-service-operator
              value: europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/sap/sap-btp-service-operator/controller:v0.7.9
            - name: kube-rbac-proxy
              value: europe-docker.pkg.dev/kyma-project/prod/external/quay.io/brancz/kube-rbac-proxy:v0.19.1
```
