### ISSUE TITLE
Old labels on BTP Operator resources are not deleted after Module Enabling

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#302]
Current behavior:
1) The BTP Operator already installed by the reconciler
2) Enable BTP Manager via Lifecycle Manager in the Kyma resource
3) BTP Operator deployment still has the label "managed-by: reconciler"

**AC**
- 1) [x] Check why it behaves like that. Our BTP Manager does k8s apply
- 2) [x] Goal is to have one to one all resources we install via BTP Manager

**Comment by jaroslaw-pieszka** [comment]
Our `apply` adds two labels `app.kubernetes.io/managed-by=btp-manager` and `chart-version=v0.4.4` so in scenario with `sap-btp-operator-controller-manager` deployment created by `reconciler` at the beginning there are:
```
Labels:                 app.kubernetes.io/instance=sap-btp-operator
                        app.kubernetes.io/name=sap-btp-operator
                        control-plane=controller-manager
                        reconciler.kyma-project.io/managed-by=reconciler
                        reconciler.kyma-project.io/origin-version=2.15.0
Annotations:            deployment.kubernetes.io/revision: 1
                        reconciler.kyma-project.io/managed-by-reconciler-disclaimer:
                          DO NOT EDIT - This resource is managed by Kyma.
                          Any modifications are discarded and the resource is reverted to the original state.
Selector:               app.kubernetes.io/instance=sap-btp-operator,app.kubernetes.io/name=sap-btp-operator,control-plane=controller-manager
```
then after module is added and LCM takes control:
```
Labels:                 app.kubernetes.io/instance=sap-btp-operator
                        app.kubernetes.io/managed-by=btp-manager
                        app.kubernetes.io/name=sap-btp-operator
                        chart-version=v0.4.4
                        control-plane=controller-manager
                        reconciler.kyma-project.io/managed-by=reconciler
                        reconciler.kyma-project.io/origin-version=2.15.0
Annotations:            deployment.kubernetes.io/revision: 4
                        reconciler.kyma-project.io/managed-by-reconciler-disclaimer:
                          DO NOT EDIT - This resource is managed by Kyma.
                          Any modifications are discarded and the resource is reverted to the original state.
```

**Comment by jaroslaw-pieszka** [comment]
If we create the deployment (reconciler is not involved) then there are following labels and annotations initially:
```
Labels:                 app.kubernetes.io/instance=sap-btp-operator
                        app.kubernetes.io/managed-by=btp-manager
                        app.kubernetes.io/name=sap-btp-operator
                        chart-version=v0.4.4
                        control-plane=controller-manager
Annotations:            deployment.kubernetes.io/revision: 1
```

**Comment by jaroslaw-pieszka** [comment]
In another scenario, after module removal `reconciler` kicks in and creates deployment again so the labels and annotations are set as follows:
```
  annotations:
    deployment.kubernetes.io/revision: "1"
    reconciler.kyma-project.io/managed-by-reconciler-disclaimer: |-
      DO NOT EDIT - This resource is managed by Kyma.
      Any modifications are discarded and the resource is reverted to the original state.
  generation: 1
  labels:
    app.kubernetes.io/instance: sap-btp-operator
    app.kubernetes.io/name: sap-btp-operator
    control-plane: controller-manager
    reconciler.kyma-project.io/managed-by: reconciler
    reconciler.kyma-project.io/origin-version: 2.15.1
```
