### ISSUE TITLE
BTP Manager: Enable new security scanning way

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#338]
Docs: https://github.tools.sap/neighbors-team/security-scanners#configuration

**AC**
- [x] 1)  scan our released version from fast and regular channels
- [x] 2) do a scan for our fresh release still not pushed to moduleTemplates
- [x] 3) scanning on main is not required for me. Let me know if you think that we need that.
- [x] 4) remove [old way](https://github.com/kyma-project/kyma/blob/main/resources/btp-manager/values.yaml) for security scans

**Comment by jaroslaw-pieszka** [comment]
Scanning on main is not executed.
For released versions we implemented scanning configuration pointing to respective image versions (tagged by release version):
PR: https://github.com/kyma-project/btp-manager/pull/357
Old way scanning is not removed yet.
Scanning pre-release versions is blocked till some extensions mentioned in https://github.tools.sap/kyma/community/issues/185 are done.

**Comment by jaroslaw-pieszka** [comment]
PR #357 released in release 0.4.9.

Scan configuration reflected in component descriptor:
```
component:
  componentReferences: []
  labels:
  - name: security.kyma-project.io/scan
    value: enabled
    version: v1
  name: kyma.project.io/module/btp-operator
  provider: internal
  repositoryContexts:
  - baseUrl: europe-docker.pkg.dev/kyma-project/prod/unsigned
    componentNameMapping: urlPath
    type: ociRegistry
  resources:
  - access:
      digest: sha256:ef296778829f99ec7bfaf45d8aded61a0173daf8b7aa61fffd600b75a5c931a1
      type: localOciBlob
    name: raw-manifest
    relation: local
    type: yaml
    version: v0.4.9
  - access:
      imageReference: europe-docker.pkg.dev/kyma-project/prod/btp-manager:0.4.9
      type: ociRegistry
    labels:
    - name: scan.security.kyma-project.io/type
      value: third-party-image
      version: v1
    name: btp-manager
    relation: external
    type: ociImage
    version: 0.4.9
  sources:
  - access:
      commit: cbc8acd845fb2d85f12b0a0b85198f57a1a86fcf
      repoUrl: github.com/kyma-project/btp-manager
      type: gitHub
    labels:
    - name: git.kyma-project.io/ref
      value: refs/heads/0.4.9
      version: v1
    - name: scan.security.kyma-project.io/language
      value: golang-mod
      version: v1
    - name: scan.security.kyma-project.io/subprojects
      value: "false"
      version: v1
    - name: scan.security.kyma-project.io/exclude
      value: '**/*_test.go'
      version: v1
    name: module-sources
    type: git
    version: v0.4.9
  version: v0.4.9
meta:
  schemaVersion: v2
```
