### ISSUE TITLE
Ensure that LeaderElection works on BTP Manager module, and there is always only one active controller

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#343]
- also check if there is a pod restart/downtime when we are doing btp manager version update

**Comment by jaroslaw-pieszka** [comment]
From the deployment spec:

```
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager

```

From btp-manager-controller-manager log:
```
I0712 13:33:18.964424       1 leaderelection.go:248] attempting to acquire leader lease kyma-system/ec023d38.kyma-project.io...
I0712 13:33:35.777618       1 leaderelection.go:258] successfully acquired lease kyma-system/ec023d38.kyma-project.io
```
