### ISSUE TITLE
Adjust memory and cpu settings

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#349]
**Description**

We have too high CPU/memory settings for our deployment.

Currently they are:
```
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
```

Adjust to:
```
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
```

**AC**

- [ ] 1) Adjust resource settings
