### ISSUE TITLE
Introduce the `kyma-project.io/module=btp-operator` label for all module resources

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/btp-manager#968]
**Description**

Accepting the [decision record](https://github.com/kyma-project/community/issues/864), we agreed to use consistent labeling for all Kyma modules. This task will verify if the agreed labeling is applied to the SAP BTP Operator module. If not, we must introduce the relevant label for all the SAP BTP Operator module resources.

`kyma-project.io/module={module_name}`

**Reasons**

Consistent labeling for Kyma modules

**Attachments**

https://github.com/kyma-project/community/issues/864

**AC**
- [x] 1) Add this label to btp manager resources
- [x] 2) Add this label to sap btp service operator resources

**Comment by PK85** [comment]
@pbochynski do we need to add that label to BTPOperator resource too?
Current default BTP Operator resource:
```
apiVersion: operator.kyma-project.io/v1alpha1
kind: BtpOperator
metadata:
  labels:
    app.kubernetes.io/name: btpoperator
    app.kubernetes.io/instance: btpoperator
    app.kubernetes.io/part-of: btp-manager
    app.kubernetes.io/managed-by: btp-manager
    app.kubernetes.io/created-by: btp-manager
  name: btpoperator
spec:
  # TODO(user): Add fields here
```
